function D = delsq2D(G, varargin)
%DELSQ2D  Construct 5-point finite difference Laplacian.
%   delsq2D(G) or delsq2D(G,[hx,hy])
%   is the sparse form of the two-dimensional,
%   5-point discrete negative Laplacian on the grid G.
%   The grid G can be generated by NUMGRID or NESTED.
%   [hx,hy] is the optional parameter for the pixel size. 
%   delsq(G) assumes hx = 1 and hy = 1.
%   The implementation assumes Dirichlet boundary conditions. 
%   Please provide a single connected component...
%   This code is a modification of the original delsq.m code from Matlab. 
%   Please see the copyright information for the original code in delsq.m

%   Modified by Ender Konukoglu, 07/12/2010. 
%   ender.konukoglu@gmail.com

[m,n] = size(G);
if nargin == 2
    hx = varargin{1}(1);
    hy = varargin{1}(2);    
else
    hx = 1;
    hy = 1;    
end;
% Indices of interior points
p = find(G);

% Connect interior points to themselves with 8's.
i = G(p);
j = G(p);
s = 2*ones(size(p))/hx^2 + 2*ones(size(p))/hy^2;

% for k = north, east, south, west
for k = [-1 1]
   % Possible neighbors in k-th direction
   Q = G(p+k);
   % Index of points with interior neighbors
   q = find(Q);
   % Connect interior points to neighbors with -1's.
   i = [i; G(p(q))];
   j = [j; Q(q)];
   s = [s; -ones(length(q),1)/hx^2];
end
for k = [m -m]
   % Possible neighbors in k-th direction
   Q = G(p+k);
   % Index of points with interior neighbors
   q = find(Q);
   % Connect interior points to neighbors with -1's.
   i = [i; G(p(q))];
   j = [j; Q(q)];
   s = [s; -ones(length(q),1)/hy^2];
end
D = sparse(i,j,s);
